### ISSUE TITLE
Make it work with futures-rs

### ISSUE THREAD

**Issue by mitsuhiko** [mitsuhiko/redis-rs#103]
Somehow we should change the library so that it can optionally work with futures. I need to figure out what the best course of action would be here.

**Comment by softprops** [comment]
+1 this to be the most complete redis client on crates.io ( there are many incomplete ones! ). it should play well with the futures ecosystem.

**Comment by mitsuhiko** [comment]
Sadly nobody came up with a good plan yet how to do that.

**Comment by softprops** [comment]
How open is this project to new contributors/maintainers breaking changes to make a futures interface happen? This issue has been open for about a year without action. I see open pull requests that are over a year old. 

I'm specifically looking for a reliable maintained redis client for use in an aws project interfacing elastic cache.

This crate seems like it has the most promise out of the batch of redis clients on crates.io but I'm a bit concerned about reliance on a client that's no longer actively maintained

**Comment by mitsuhiko** [comment]
> breaking changes

Zero. But if you can make it work where a separate API is installed then 100%. The sync interface must stay functional and stay ergonomic as for the vast majority of users I think async will never play a role.

**Comment by carllerche** [comment]
A sync interface can always be layered on top of an async one by using the blocking future primitives.

**Comment by mitsuhiko** [comment]
@carllerche i'm not sure if that's such a great idea performance wise but I let others convince me. I *think* that sync mode is more important in Rust than async but that's just a hunch.

**Comment by jwilm** [comment]
@mitsuhiko the only real overhead with @carllerche's approach is `epoll` or whichever event API. There won't be any cross-thread communication overhead since the event loop can just run on main thread. It's also a big win in terms of maintainability since sync APIs are a thin wrapper on async API. For instance, a sync `hget` wrapper might look like:

```rust
fn hget<K: ToRedisArgs, F: ToRedisArgs, RV: FromRedisValue>(&self, key: K, field: F) -> RedisResult<RV> {
    self.core.run(self.async_client.hget(key, field))
        .map_err(From::from)
}
```

which could easily be implemented by a macro for all of the sync API.

**Comment by Marwes** [comment]
I am looking into implementing this.

After going through the Repo I believe that the best way is to duplicate `ConnectionLike` to a `AsyncConnectionLike` trait. Trying to merge these concepts with minimal or no overhead may be possible but for a first draft I believe it to be to complicated so I rather start from scratch and work my way back in that case.

```rust
pub trait AsyncConnectionLike {
    fn req_packed_command(self, cmd: Vec<u8>) -> RedisFuture<(Self, Value)>;

    ....
}
```

The `connection` module the `commands` module also need to be changed. Since this is largely generated by macros already I should be able to extend these macros to generate async variants of each method as well.

The `parser` module will need some changes as well to work with async io. Ideally this should be a state machine capable of resuming parsing more or lesse anywhere in the input but I may start with a simpler variant which just tries to parse from a `&[u8]` repeatedly, restarting from the top anytime it does not have enough data.

Lastly, as an optional change I noticed that there is currently a `RefCell` wrapping the connection. https://github.com/mitsuhiko/redis-rs/blob/0a54fd9446c09aaa4efa30076ec0ce579bfb4bfb/src/connection.rs#L166

This is not necessary with some refactoring to make `ConnectionLike` take `&mut self` instead (and also propagating this change everywhere). Though this might make some programs harder to write, it should also prevent some programmer errors as well (prevents issuing new requests while still reading responses from an earlier request). But I might be wrong about this. I can make a PR of it if it sounds like a good idea.

**Comment by mitsuhiko** [comment]
@Marwes more than happy to merge work that makes this work! The proposal seems reasonable. I don't mind if we end up with two apis.
