### ISSUE TITLE
Storing `Vec<u16>` as the value fails when `Vec<u8>` works

### ISSUE THREAD

**Issue by PureW** [mitsuhiko/redis-rs#296]
How come the following program fails?
```
use redis::{Client, Commands};

fn main() {
    let redis_client = Client::open("redis://127.0.0.1/").unwrap();
    let mut redis_conn = redis_client.get_connection().unwrap();

    let key = 1177;
    let val: Vec<u16> = vec![11, 12];

    let res: Result<(), redis::RedisError> = redis_conn.set(key, val);
    res.unwrap();

    let vals: Vec<u16> = redis_conn.get(key).unwrap();
    println!("Received {:?}", vals);
}
```

It fails with
`thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: An error was signalled by the server: syntax error', src/libcore/result.rs:1188:5`

Switching the `u16` to `u8` works.

**Comment by badboy** [comment]
This is what we send with `u16`:
```
"SET" "1177" "11" "12"
```

And this with `u8`:
```
"SET" "1177" "\x0b\x0c"
```

That's because we treat `Vec<u8>` as a byte buffer, but `Vec<T>` for all other `T` as a list of arguments.
Which to me makes sense: for the most part it should be the user's responsibility to convert to the format they need to store and a byte buffer is the most simplistic form it can be (e.g. anything for any bigger value how should redis-rs know which byte order you'd want?)

In your case you will need to turn the `Vec<u16>` into a `Vec<u8>` (of twice the length).

**Comment by PureW** [comment]
Should `Vec<u16>` really implement `ToRedisArgs` in that case?

**Comment by badboy** [comment]
It's hard to disallow that. We do want `ToRedisArgs` for u16 and encode it as its ASCII representation. If that doesn't work for you encoding is up to you.

The fact that it then works for `Vec<u16>` is because we also want `Vec<T: ToRedisArgs>` to work as multiple arguments (again: except for `u8` which we treat as a buffer).

Under the current design there's no way we can support all the different cases.
I do agree that it's not necessarily straight forward and could at the very least require a bit more documentation.
