### ISSUE TITLE
every 3s get `Response was of incompatible type`

### ISSUE THREAD

**Issue by cssivision** [mitsuhiko/redis-rs#308]
```rs
tokio::spawn(|| {
    async fn check(&self, conn: &mut Self::Connection) -> io::Result<()> {
        while {
            sleep(3s).await;

            redis::cmd("PING")
                .query_async(conn)
                .await
                .map_err(|e| other(&e.to_string()))
        }
    }
|)

let result = conn.get(keys).await;
```
every 3s get a `result` Err:
```
Err(Response was of incompatible type: "Response type not vector compatible." (response was status("PONG")))
```

**Comment by badboy** [comment]
If you keep doing the same, you will keep getting the same result ;)

I guess it is because it tries to decode the answer as `Vec<u8>`, but it sees a `Value::Status` and then can't decode it (this happens [in this implementation](https://github.com/mitsuhiko/redis-rs/blob/1ea0bd0c2e7b450eb5279995142fd64e5db0fa69/src/types.rs#L1019)).
If you explicitly specify the return type it might work:

```rust
let result: String = redis::cmd("PING")
	.query_async(conn)
    .await
    .map_err(|e| other(&e.to_string()))?
```

(oh, also your loop never returns, so not sure if that's because you trimmed it down or it's your actual code, I "fixed" it in my example above)

**Comment by cssivision** [comment]
> If you keep doing the same, you will keep getting the same result ;)
> 
> I guess it is because it tries to decode the answer as `Vec<u8>`, but it sees a `Value::Status` and then can't decode it (this happens [in this implementation](https://github.com/mitsuhiko/redis-rs/blob/1ea0bd0c2e7b450eb5279995142fd64e5db0fa69/src/types.rs#L1019)).
> If you explicitly specify the return type it might work:
> 
> ```rust
> let result: String = redis::cmd("PING")
> 	.query_async(conn)
>     .await
>     .map_err(|e| other(&e.to_string()))?
> ```
> 
> (oh, also your loop never returns, so not sure if that's because you trimmed it down or it's your actual code, I "fixed" it in my example above)

the return value should be explicit, fixed by following: 
```rust
let result: Value::Status = redis::cmd("PING")
	.query_async(conn)
    .await
    .map_err(|e| other(&e.to_string()))?
```
