### ISSUE TITLE
Deciding on ongoing maintainership

### ISSUE THREAD

**Issue by badboy** [mitsuhiko/redis-rs#376]
In #360 @weihanglo brought up the question about maintainership again (fair point!) because that PR has been lingering for a while.

In the past months most of the code and review has been handled by @Marwes, thanks for that!
I myself didn't had much time to do anything.

Going forward I will drop out as a maintainer due to lack of time and energy for this project.

At the moment me and @mitsuhiko (original creator) have permissions on crates.io. We need to expand that.
@Marwes should probably get that permission too.
@mitsuhiko Any objections?

Beyond that I would leave it up to Marwes (and probably mitsuhiko, given it still runs as a project under his GitHub account) to expand the mainainer team further.

**Comment by Marwes** [comment]
I will continue to help in the capacity that I can atleast, though since I have more than enough projects outside of work and I only use redis-rs at work, I only have time to the extent that my work allows/needs it. (As I was away from work for a few weeks over summer I didn't have any capacity to work on redis over the summer, for instance).

**Comment by weihanglo** [comment]
I have already started helping this project by reviewing issues and pull requests these days. Since @Marwes will be back after this summer and the project continues moving forward, that's fine for me to keep contributing in the same manner. If @Marwes need someone to share the actual works, I also appreciate for any further maintenance opportunity :)

**Comment by Terkwood** [comment]
@weihanglo  -- thanks for your recent efforts in reviewing PRs and contributing changes.  I think it would help streamline submissions if you had the ability to merge PRs.  

We have a lot of different people raising issues and a number of people submitting pull requests. Reducing the calendar time required for merges will help us gain momentum.

Thanks as always to the original authors and maintainers, this project has become a staple in the rust community and has great overall coverage in terms of DB features.

**Comment by Marwes** [comment]
Any chance of getting access to crates.io soon?

**Comment by badboy** [comment]
> Any chance of getting access to crates.io soon?

you should have an invite.

**Comment by Marwes** [comment]
Accepted! Thanks!
