### ISSUE TITLE
What is the benefit of MultiplexedConnection?

### ISSUE THREAD

**Issue by mfrlin** [mitsuhiko/redis-rs#453]
This simple example of a worker that receives jobs from redis hangs when trying to send results back. It seems to me that I need multiple connections for my example or can I make it work with cloning `MultiplexedConnection`?

```
use redis::{AsyncCommands, RedisResult, aio::{ConnectionManager}};
use tokio::time::{sleep, Duration};
use tokio::task;

#[tokio::main]
async fn main() {
    let client = redis::Client::open("redis://127.0.0.1/").unwrap();
    let mut connection = loop {
        match client.get_tokio_connection_manager().await {
            Ok(mngr) => break mngr,
            Err(e) => println!("MAIN errror {:?}", e),
        }
        println!("MAIN waiting 5 sec");
        sleep(Duration::from_secs(5)).await;
    };
    
    loop {
        println!("MAIN getting from queue");
        let result: redis::RedisResult<(String, String)> = connection.blpop("queue:worker", 0).await;
        if let Ok(value) = result {
            println!("MAIN received job {:?}", value);
            task::spawn(process_job(value.1, connection.clone()));
        } else {
            println!("MAIN error. waiting 5 sec");
            sleep(Duration::from_secs(5)).await;
        }
    }
}

async fn process_job(job: String, mut connection: ConnectionManager) {
    println!("PROCESSING started {}", job);
    let result: usize = connection.rpush("queue:result", String::from("result") + &job).await.unwrap();
    println!("PROCESSING done {}", job);
}
```

Output:
```
MAIN getting from queue
MAIN received job ("queue:worker", "job-1")
MAIN getting from queue  // blocking without timeout
PROCESSING started job-1 // tries to send the result
// hangs here until I send new job which "releases" blpop
PROCESSING done job-1
MAIN received job ("queue:worker", "job-2")
MAIN getting from queue
PROCESSING started job-2
```

**Comment by Marwes** [comment]
If you use blocking operations like `blpop` they will block any other clients from running commands until `blpop` returns. It is just the way redis works in conjunction with `MultiplexedConnection`

**Comment by mfrlin** [comment]
I still don't understand what `MultiplexedConnection` gives me? Could I use two connections - one for blpop (receiving jobs) and one for rpush (sending results)? I would like to avoid creating new connection for each result because there will be potentially many jobs at once. I would also prefer not to implement a connection pool if it can be avoided.

**Comment by Marwes** [comment]
`MultiplexedConnection` lets you send multiple, independent requests without having to wait for each response. However, as the responses still has to return in the same order as the requests, any query that blocks will end up blocking all later commands on the connection.

For most commands this isn't a problem, as redis is already single threaded (currently at least), commands would be effectively serialized anyway.

So for any connections you want to use a blocking operation with you should use a separate connection.

**Comment by mfrlin** [comment]
Ok, thank you.

**Comment by kodmanyagha** [comment]
I wasted 2 days for finding reason of blocking operations not waiting for specified time and after 2 days I found the main problem. In `MultiplexedConnection` there is a function name is `set_response_timeout` and this is setting all commands max wait time includes blocking operations. I measured it and it seems its default value is 0.5 second. If you want to work with blocking operations like `blpop` you must increase this value and also you have to be sure that you're using this connection for only this operation. Otherwise it will wait only 0.5 second and then continue. Neighter google nor AI answered me like that and bcs of that I want to write this information to here after 5 years.

Yes, I investigated almost all functions one by one in all redis-rs library and I found the small mouse: https://docs.rs/redis/latest/redis/aio/struct.MultiplexedConnection.html#method.set_response_timeout

Let me share my code:

```
let mut conn = self
    .bb8_pool
    // Important part is here, just one dedicated connection for only using blocking operation
    .dedicated_connection()
    .await
    .map_err(|err| anyhow::anyhow!("Err: {err}"))?;

conn.set_response_timeout(std::time::Duration::from_secs(30));

let job_result: Option<(String, String)> = conn
    .blpop(&result_key, 10_f64) // Now it is really waits for 10 seconds :)
    .await
    .context(anyhow::anyhow!(queue_consts::ERROR_TIMEOUT))?;
```
