### ISSUE TITLE
Add support for ToRedisArgs  for &std::string::String 

### ISSUE THREAD

**Issue by allan-simon** [mitsuhiko/redis-rs#84]
right now i need to do 

```rust
connection.pfadd(
     my_key.as_bytes(),
     my_value.as_bytes(),
)
```

it would be great if i could do 

```rust
connection.pfadd(
     &my_key,
     &my_value,
)
```
if there's no underlying reason blocking things, I can propose you a PR

**Comment by badboy** [comment]
```rust
connection.pfadd(
     &my_key[..],
     &my_value[..],
)
```

should just work, as we already have `ToRedisArgs` for `&str`. But because it is generic `&String` does not coerce to `&str` here. 
See https://github.com/mitsuhiko/redis-rs/blob/dfa47519578e19389873dbbe57f2cbf8dfc9a79c/src/types.rs#L497

The following would be necessary to support `&String` without any more user help:
```rust
impl<'a> ToRedisArgs for &'a String {
    fn to_redis_args(&self) -> Vec<Vec<u8>> {
        vec![self.as_bytes().to_vec()]
    }
}
```

@mitsuhiko: What do you think?

**Comment by mitsuhiko** [comment]
Sounds like a reasonable thing to add.
